name: courses2
description: Une application Flutter pour gérer ses courses.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.0
  json_annotation: ^4.0.0
  localstorage:
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^4.0.2
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/courses.json
