name: courses3
description: Une application Flutter connectée pour gérer ses courses.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 3.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  localstorage: ^4.0.0+1
  logging:
  http: ^0.13.1
  courses_sse_client:
    git: git@github.com:abasty/courses_sse_client.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
  assets:
    - assets/courses.json
