name: courses2
version: 0.1.0
summary: Courses2
description: Une application Flutter pour faire ses courses2.

confinement: strict
base: core18
grade: stable

apps:
  courses2:
    command: courses2
    extensions: [flutter-dev]
    plugs:
    - network

parts:
  courses2:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
