name: stocks
version: 0.1.0
summary: Stocks
description: Une application Flutter pour faire ses stocks.

confinement: strict
base: core18
grade: stable

apps:
  stocks:
    command: stocks
    extensions: [flutter-dev]
    plugs:
    - network

parts:
  stocks:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
