name: courses3
version: 0.1.0
summary: courses3
description: Une application Flutter pour faire ses courses.

confinement: strict
base: core18
grade: stable

apps:
  courses3:
    command: courses3
    extensions: [flutter-dev]
    plugs:
    - network

parts:
  courses3:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
